@startuml
Interface Aggregate {

  iterator()
}
Interface Iterator {

  has_next()
  next()
}
class ConcreteAggregate {

  iterator()
}
class ConcreteIterator {

  has_next()
  next()
}

Aggregate -> Iterator: create >
ConcreteIterator o-left-> ConcreteAggregate
ConcreteAggregate .up.|> Aggregate
ConcreteIterator .up.|> Iterator
@enduml
